Adding Support to GCP
vectra-ai-research/Halberd pull request #37
Opened 2024-11-20 15:11 UTC by jesayafn

# Adding Support to GCP
Related issue: #30 

## Feature enhancement:
- New Attack Surface 
- New GCP Attack Technique:  **GCPEstablishAccessAsServiceAccount**
- Capability to save GCP credential

2024-11-20 15:12 UTC, jesayafn commented
Hi @openrec0n, can you add "WIP" label on this PR?

2024-11-26 02:09 UTC, jesayafn commented
Hi @openrec0n, you can review the PR

2024-11-27 06:44 UTC, openrec0n commented
@jesayafn thanks for the PR. I am reviewing this

2024-12-21 19:42 UTC, openrec0n requested changes
@jesayafn Please check the comments and implement the suggested changes.

2024-12-21 19:42 UTC, openrec0n commented on Halberd.py
> +'''C062 - Callback to generate GCP session options in AWS sessions dropdown'''
```suggestion
'''C062 - Callback to generate GCP session options in GCP sessions dropdown'''
```

2024-12-21 19:42 UTC, openrec0n commented on Halberd.py
> +'''C062 - Callback to generate GCP session options in AWS sessions dropdown'''
```suggestion
'''C062 - Callback to generate GCP session options in GCP sessions dropdown'''
```

2024-12-21 19:42 UTC, openrec0n commented on attack_techniques/gcp/gcp_establish_access_as_sa.py
> +            set
```suggestion
```

2024-12-21 19:42 UTC, openrec0n commented on attack_techniques/gcp/gcp_establish_access_as_sa.py
> +            # Input validationc
```suggestion
            # Input validation
```

2024-12-21 19:42 UTC, openrec0n commented on attack_techniques/gcp/gcp_establish_access_as_sa.py
> +                "message": f"Successfully established access to target Azure tenant"
```suggestion
                "message": f"Successfully established access to target GCP tenant"
```

2024-12-21 19:42 UTC, openrec0n commented on attack_techniques/gcp/gcp_establish_access_as_sa.py
> +                "value": caller_info_output,
```suggestion
                "value": {
                    "credential_info": caller_info_output,
                    "access_status": {
                        "saved": save_and_activate,
                        "activated": save_and_activate,
                        "scopes": current_access.scopes,
                        "token_expiry": str(current_access.expiry) if current_access.expiry else None
                    }
                }
```

2024-12-21 19:42 UTC, openrec0n commented on attack_techniques/gcp/gcp_establish_access_as_sa.py
> +                "value": caller_info_output,
Suggested change to return a more detailed output with access information

2024-12-21 19:42 UTC, openrec0n commented on core/gcp/gcp_access.py
> +
```suggestion
    
```

2024-12-21 19:42 UTC, openrec0n commented on core/gcp/gcp_access.py
> +
@jesayafn these comments can be cleared out

2024-12-21 19:42 UTC, openrec0n commented on core/gcp/gcp_access.py
> +from typing import Union
```suggestion
```

2024-12-21 19:42 UTC, openrec0n commented on core/gcp/gcp_access.py
> +from typing import Union
Suggested change to remove import since its not being used

2024-12-24 03:19 UTC, jesayafn commented on Halberd.py
> +            if current_access["credential"]["type"] == "service_account":
![image](https://github.com/user-attachments/assets/092e0837-951f-4186-b97f-d225e4f1d606)

`current_access` has a `type` field under `credential` dict.

2024-12-24 23:04 UTC, openrec0n approved these changes

2024-12-24 23:05 UTC, merged